// Dump a SQLite database's rows as multi-row INSERT statements, one
// statement per table, FK-dependency ordered. Used to seed D1 from the
// VPS-era SQLite file (see infra README). Schema itself comes from the
// drizzle migrations; this emits data only.
//
// D1 rejects oversized statements, so output is split across several
// alchemy-style migration folders (namePrefix_NN/migration.sql), each kept
// under MAX_BYTES.
//
// Sensitive user and billing tables are excluded unless --include-sensitive
// is explicitly supplied.
//
//   node scripts/d1-dump.mjs <input.sqlite> <outputDir> <namePrefix> [--include-sensitive]
import Database from "better-sqlite3";
import { mkdirSync, writeFileSync } from "node:fs";

const [, , inputPath, drizzleDir, namePrefix] = process.argv;
const includeSensitive = process.argv.includes("--include-sensitive");
if (!inputPath || !drizzleDir || !namePrefix) {
  console.error(
    "usage: node scripts/d1-dump.mjs <input.sqlite> <outputDir> <namePrefix> [--include-sensitive]",
  );
  process.exit(1);
}

const MAX_BYTES = 64 * 1024;
const STATEMENT_BUDGET = 24 * 1024;

// Insert order satisfies FK constraints (users/stock before dependents).
const PUBLIC_TABLE_ORDER = [
  "stock",
  "stock_metrics",
  "stock_memory",
  "stock_analysis",
  "daily_signal",
  "supervisor_alert",
];
const SENSITIVE_TABLE_ORDER = ["user", "watchlist", "usage_log", "wallet_top_up", "oauth_state"];
const TABLE_ORDER = includeSensitive
  ? [
      SENSITIVE_TABLE_ORDER[0],
      ...PUBLIC_TABLE_ORDER.slice(0, 3),
      SENSITIVE_TABLE_ORDER[1],
      ...PUBLIC_TABLE_ORDER.slice(3),
      ...SENSITIVE_TABLE_ORDER.slice(2),
    ]
  : PUBLIC_TABLE_ORDER;

function sqlValue(value) {
  if (value === null || value === undefined) return "NULL";
  if (Number.isFinite(value)) return String(value);
  if (value?.constructor === BigInt) return String(value);
  if (value instanceof Date) return `'${value.toISOString()}'`;
  if (Buffer.isBuffer(value)) return `X'${value.toString("hex")}'`;
  return `'${String(value).replaceAll("'", "''")}'`;
}

function insertStatement(table, columns, tuples) {
  const colList = columns.map((c) => `"${c}"`).join(", ");
  return `INSERT INTO "${table}" (${colList}) VALUES\n${tuples.join(",\n")};`;
}

const db = new Database(inputPath, { readonly: true });
const statements = [];

for (const table of TABLE_ORDER) {
  const exists = db
    .prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name = ?")
    .get(table);
  if (!exists) continue;

  const rows = db.prepare(`SELECT * FROM "${table}"`).all();
  if (rows.length === 0) continue;

  const columns = Object.keys(rows[0]);
  if (!includeSensitive && table === "stock_analysis") {
    for (const row of rows) row.last_triggered_by_user_id = null;
  }
  let pending = [];
  let bytes = 0;

  const flush = () => {
    if (pending.length === 0) return;
    statements.push(insertStatement(table, columns, pending));
    pending = [];
    bytes = 0;
  };

  for (const row of rows) {
    const tuple = `(${columns.map((c) => sqlValue(row[c])).join(", ")})`;
    // A single row over budget still becomes its own statement — the file
    // packer splits at statement granularity and D1's cap is higher.
    if (bytes > 0 && bytes + tuple.length > STATEMENT_BUDGET) flush();
    pending.push(tuple);
    bytes += tuple.length;
  }
  flush();

  console.log(`${table}: ${rows.length} rows`);
}
db.close();

// Pack statements into migration files under the byte cap.
const files = [];
let current = [];
let size = 0;

for (const statement of statements) {
  if (size + statement.length > MAX_BYTES && current.length > 0) {
    files.push(current.join("\n\n"));
    current = [];
    size = 0;
  }
  current.push(statement);
  size += statement.length;
}
if (current.length > 0) files.push(current.join("\n\n"));

files.forEach((body, i) => {
  const folder = `${drizzleDir}/${namePrefix}_${String(i + 1).padStart(2, "0")}`;
  mkdirSync(folder, { recursive: true });
  const sql = `-- generated by scripts/d1-dump.mjs — data only (part ${i + 1}/${files.length})\n\n${body}\n`;
  writeFileSync(`${folder}/migration.sql`, sql);
  console.log(`wrote ${folder}/migration.sql (${sql.length} bytes)`);
});
