/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreenRouteImport } from './routes/screen'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SymbolRouteImport } from './routes/$symbol'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksSymbolRouteImport } from './routes/stocks.$symbol'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiScreenRunRouteImport } from './routes/api/screen/run'
import { Route as ApiScreenOutcomesRouteImport } from './routes/api/screen/outcomes'
import { Route as ApiScreenJevRouteImport } from './routes/api/screen/jev'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthGoogleStartRouteImport } from './routes/api/auth/google/start'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'

const ScreenRoute = ScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SymbolRoute = SymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksSymbolRoute = StocksSymbolRouteImport.update({
  id: '/stocks/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenRunRoute = ApiScreenRunRouteImport.update({
  id: '/api/screen/run',
  path: '/api/screen/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenOutcomesRoute = ApiScreenOutcomesRouteImport.update({
  id: '/api/screen/outcomes',
  path: '/api/screen/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenJevRoute = ApiScreenJevRouteImport.update({
  id: '/api/screen/jev',
  path: '/api/screen/jev',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleStartRoute = ApiAuthGoogleStartRouteImport.update({
  id: '/api/auth/google/start',
  path: '/api/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$symbol': typeof SymbolRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/screen': typeof ScreenRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/health': typeof ApiHealthRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/screen/jev': typeof ApiScreenJevRoute
  '/api/screen/outcomes': typeof ApiScreenOutcomesRoute
  '/api/screen/run': typeof ApiScreenRunRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$symbol': typeof SymbolRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/screen': typeof ScreenRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/health': typeof ApiHealthRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/screen/jev': typeof ApiScreenJevRoute
  '/api/screen/outcomes': typeof ApiScreenOutcomesRoute
  '/api/screen/run': typeof ApiScreenRunRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$symbol': typeof SymbolRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/screen': typeof ScreenRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/health': typeof ApiHealthRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/screen/jev': typeof ApiScreenJevRoute
  '/api/screen/outcomes': typeof ApiScreenOutcomesRoute
  '/api/screen/run': typeof ApiScreenRunRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$symbol'
    | '/about'
    | '/dashboard'
    | '/screen'
    | '/api/analyze'
    | '/api/health'
    | '/stocks/$symbol'
    | '/api/auth/signout'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/screen/jev'
    | '/api/screen/outcomes'
    | '/api/screen/run'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$symbol'
    | '/about'
    | '/dashboard'
    | '/screen'
    | '/api/analyze'
    | '/api/health'
    | '/stocks/$symbol'
    | '/api/auth/signout'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/screen/jev'
    | '/api/screen/outcomes'
    | '/api/screen/run'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
  id:
    | '__root__'
    | '/'
    | '/$symbol'
    | '/about'
    | '/dashboard'
    | '/screen'
    | '/api/analyze'
    | '/api/health'
    | '/stocks/$symbol'
    | '/api/auth/signout'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/screen/jev'
    | '/api/screen/outcomes'
    | '/api/screen/run'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SymbolRoute: typeof SymbolRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  ScreenRoute: typeof ScreenRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiHealthRoute: typeof ApiHealthRoute
  StocksSymbolRoute: typeof StocksSymbolRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiScreenJevRoute: typeof ApiScreenJevRoute
  ApiScreenOutcomesRoute: typeof ApiScreenOutcomesRoute
  ApiScreenRunRoute: typeof ApiScreenRunRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleStartRoute: typeof ApiAuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screen': {
      id: '/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$symbol': {
      id: '/$symbol'
      path: '/$symbol'
      fullPath: '/$symbol'
      preLoaderRoute: typeof SymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$symbol': {
      id: '/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screen/run': {
      id: '/api/screen/run'
      path: '/api/screen/run'
      fullPath: '/api/screen/run'
      preLoaderRoute: typeof ApiScreenRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screen/outcomes': {
      id: '/api/screen/outcomes'
      path: '/api/screen/outcomes'
      fullPath: '/api/screen/outcomes'
      preLoaderRoute: typeof ApiScreenOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screen/jev': {
      id: '/api/screen/jev'
      path: '/api/screen/jev'
      fullPath: '/api/screen/jev'
      preLoaderRoute: typeof ApiScreenJevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/start': {
      id: '/api/auth/google/start'
      path: '/api/auth/google/start'
      fullPath: '/api/auth/google/start'
      preLoaderRoute: typeof ApiAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SymbolRoute: SymbolRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  ScreenRoute: ScreenRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiHealthRoute: ApiHealthRoute,
  StocksSymbolRoute: StocksSymbolRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiScreenJevRoute: ApiScreenJevRoute,
  ApiScreenOutcomesRoute: ApiScreenOutcomesRoute,
  ApiScreenRunRoute: ApiScreenRunRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleStartRoute: ApiAuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
